server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/**

management:
  endpoints:
    web:
      exposure:
        include: health, info  # Habilita los endpoints health e info
  endpoint:
    health:
      show-details: always  # Muestra todos los detalles en /actuator/health


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
